name: Release

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  call-release-workflow:
    uses: infralight/.github/.github/workflows/github-release.yaml@master
    secrets:
      RELEASE_GITHUB_TOKEN: ${{ secrets.GLOBAL_PAT }}